### ISSUE TITLE
Handle with \0 at the end.

### ISSUE THREAD

**Issue by loconox** [bzikarsky/react-gearman#7] opened 2017-05-02 16:18 UTC
Hi there,

I recently include this lib into my project. I facing an issue when a gearman worker crashed during the execution of a non-async job.
Logs :
```
  [Zikarsky\React\Gearman\Command\Exception]                                      
  Unexpected WORK_FAIL(14)[job_handle=H:iMac-de-loconox.local:89\0]. Task unknown
```
(I rewrote the \0 at the end because it doesn't print correctly into my terminal)

The problem is that the gearman server responds with an handle name ending with \0 whereas tasks in array in Zikarsky\React\Gearman\Client are stored without this \0.

**Comment by loconox** [comment] 2017-05-03 09:53
I think I have found the issue. See https://github.com/loconox/react-gearman/commit/dc374688293c67cba277f7521dfc53ccfd68d1e0

**Comment by bzikarsky** [comment] 2017-05-03 20:22
Strange. The spec defines WORK_FAIL with only a single argument 'job_handle'. The `\0` is the standard delimiter for arguments and shouldn't cause trouble. Can you maybe try to define a testcase for the failure, so we can fix against a unittest?

**Comment by bzikarsky** [comment] 2017-05-07 17:57
Okay, I had a deeper look into this:

The problem is in an incorrect usage of the `$limit`-parameter of PHP's `explode()` in [`..\ReadBuffer::handleBody`](https://github.com/bzikarsky/react-gearman/blob/master/src/Command/Binary/ReadBuffer.php#L164). 

This breaks the parsing of every command's last parameter if it is not `DATA` (maybe even data, it did not verify this yet). I demonstrated the problem in https://3v4l.org/EK67j.

The `explode`-call is limited to the number of arguments defined in the command-definition (which is `1` for `WORK_FAIL`). This allows binary `DATA` to contain `\0`-bytes, but doesn't remove the trailing `\0` (used as an argument-delimiter) on other argument-types.

My proposed fix for this problem is:

- Verify: Does the `\0`-byte also get added to `DATA`-arguments?
- If yes: Just keep the existing explode-limit-logic, but use `substr($buffer, 0, .-1)` to exclude the trailing `\0`
- If no: Use the yes variant, but find an elegant way to handle the `DATA`-exception

This also means we need a test for those edge-cases in [ReadBufferTest](https://github.com/bzikarsky/react-gearman/blob/master/tests/Command/Binary/ReadBufferTest.php).

I'll close your PR unmerged for now. Let me know if you want to work on the fix for this deeper issue or if you want me to allocate some time next week :smile:.

**Comment by loconox** [comment] 2017-05-09 11:07
Well, I re-read the the doc and concluded that this could be a bug in the server implementation or in the doc. http://gearman.org/protocol/ 

Since `\0` is the argument delimiter, their should not has a `\0` at the end of a `WORK_FAIL` respond. For example, in the case of a `JOB_CREATED` response, where the last argument is a `job_handle`, there isn't `\0` at the end.

First case, `JOB_CREATED` followed by `WORK_COMPLETE` :
```
\x00RES\x00\x00\x00\x08\x00\x00\x00\x19H:iMac-de-loconox.local:5
\x00RES\x00\x00\x00\r\x00\x00\x00\x1EH:iMac-de-loconox.local:5\x00toto
```

Second case, `JOB_CREATED` followed by `WORK_FAIL` :
```
\x00RES\x00\x00\x00\x08\x00\x00\x00\x19H:iMac-de-loconox.local:7
\x00RES\x00\x00\x00\x0E\x00\x00\x00\x1AH:iMac-de-loconox.local:7\x00
```

**Comment by bzikarsky** [comment] 2017-05-09 12:47
I agree. That's pretty much the same conclusion I had. What do you propose?

Maybe just adding `DATA` to the command-definition of WORK_FAIL is the right fix. In that case we should mention in a comment that some gearmand implementations behave this way, even though it's not in the protocol definition.

**Comment by loconox** [comment] 2017-05-09 12:48
I've opened an issue in the server repo to know their opinion. https://github.com/gearman/gearmand/issues/108

**Comment by loconox** [comment] 2017-05-09 12:51
Yep, as I fixed this issue in my repo https://github.com/loconox/react-gearman/tree/fix-workfail I suggest to add a `DATA` argument to the `WORK_FAIL` response and add a commentary to explain why. I'm updating my branch and make a PR.

**Comment by bzikarsky** [comment] 2017-05-09 12:54
Great, thanks!

**Closed** 2017-05-09 13:37 UTC
